"""baseline_schema

Revision ID: cd4ad910d3fe
Revises: 
Create Date: 2026-03-11 17:20:17.124627

"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cd4ad910d3fe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_event_timestamp", "audit_logs", ["event_type", "timestamp"], unique=False)
    op.create_index("idx_audit_user_timestamp", "audit_logs", ["user_id", "timestamp"], unique=False)
    op.create_index(op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Enum("GITLAB", name="sourcecontrolproviderenum"), nullable=False),
        sa.Column("gitlab_project_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path_with_namespace", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("clone_url", sa.String(length=500), nullable=False),
        sa.Column("default_branch", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CLONING",
                "PARSING",
                "EXTRACTING",
                "EMBEDDING",
                "COMPLETED",
                "FAILED",
                name="repositorystatusenum",
            ),
            nullable=True,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_commit_sha", sa.String(length=40), nullable=True),
        sa.Column("total_files", sa.Integer(), nullable=True),
        sa.Column("total_symbols", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("manifesto", sa.Text(), nullable=True),
        sa.Column("ai_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_repo_gitlab_project", "repositories", ["gitlab_project_id"], unique=False)
    op.create_index("idx_repo_provider_path", "repositories", ["provider", "path_with_namespace"], unique=False)
    op.create_index("idx_repo_status_updated", "repositories", ["status", "updated_at"], unique=False)
    op.create_index(op.f("ix_repositories_gitlab_project_id"), "repositories", ["gitlab_project_id"], unique=False)
    op.create_index(op.f("ix_repositories_provider"), "repositories", ["provider"], unique=False)
    op.create_index(op.f("ix_repositories_status"), "repositories", ["status"], unique=False)
    op.create_table(
        "commits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("sha", sa.String(length=40), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("author_email", sa.String(length=255), nullable=True),
        sa.Column("committed_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_sha", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_commits_repository_id"), "commits", ["repository_id"], unique=False)
    op.create_index(op.f("ix_commits_sha"), "commits", ["sha"], unique=True)
    op.create_table(
        "docker_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=True),
        sa.Column("container_name", sa.String(length=255), nullable=True),
        sa.Column("build_context", sa.String(length=1000), nullable=True),
        sa.Column("dockerfile", sa.String(length=500), nullable=True),
        sa.Column("build_args", sa.JSON(), nullable=True),
        sa.Column("ports", sa.JSON(), nullable=True),
        sa.Column("expose", sa.JSON(), nullable=True),
        sa.Column("networks", sa.JSON(), nullable=True),
        sa.Column("depends_on", sa.JSON(), nullable=True),
        sa.Column("links", sa.JSON(), nullable=True),
        sa.Column("environment", sa.JSON(), nullable=True),
        sa.Column("volumes", sa.JSON(), nullable=True),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("entrypoint", sa.Text(), nullable=True),
        sa.Column("working_dir", sa.String(length=1000), nullable=True),
        sa.Column("user", sa.String(length=100), nullable=True),
        sa.Column("restart", sa.String(length=50), nullable=True),
        sa.Column("healthcheck", sa.JSON(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.Column("service_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "file_path", "service_name", name="uq_docker_service_repo_file_name"),
    )
    op.create_index("idx_docker_service_image", "docker_services", ["image"], unique=False)
    op.create_index("idx_docker_service_name", "docker_services", ["service_name"], unique=False)
    op.create_index("idx_docker_service_repo", "docker_services", ["repository_id"], unique=False)
    op.create_index(op.f("ix_docker_services_repository_id"), "docker_services", ["repository_id"], unique=False)
    op.create_index(op.f("ix_docker_services_service_name"), "docker_services", ["service_name"], unique=False)
    op.create_table(
        "gateway_routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("gateway_type", sa.String(length=50), nullable=False),
        sa.Column("downstream_path_template", sa.String(length=2000), nullable=True),
        sa.Column("upstream_path_template", sa.String(length=2000), nullable=True),
        sa.Column("upstream_host", sa.String(length=500), nullable=True),
        sa.Column("upstream_port", sa.Integer(), nullable=True),
        sa.Column("http_methods", sa.JSON(), nullable=True),
        sa.Column("route_name", sa.String(length=500), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("route_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository_id",
            "file_path",
            "downstream_path_template",
            "gateway_type",
            name="uq_gateway_route_repo_file_path_type",
        ),
    )
    op.create_index("idx_gateway_route_downstream", "gateway_routes", ["downstream_path_template"], unique=False)
    op.create_index("idx_gateway_route_repo", "gateway_routes", ["repository_id"], unique=False)
    op.create_index("idx_gateway_route_type", "gateway_routes", ["gateway_type"], unique=False)
    op.create_index("idx_gateway_route_upstream_host", "gateway_routes", ["upstream_host"], unique=False)
    op.create_index(
        op.f("ix_gateway_routes_downstream_path_template"), "gateway_routes", ["downstream_path_template"], unique=False
    )
    op.create_index(op.f("ix_gateway_routes_gateway_type"), "gateway_routes", ["gateway_type"], unique=False)
    op.create_index(op.f("ix_gateway_routes_repository_id"), "gateway_routes", ["repository_id"], unique=False)
    op.create_index(op.f("ix_gateway_routes_upstream_host"), "gateway_routes", ["upstream_host"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=True),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", "RETRYING", name="jobstatusenum"),
            nullable=False,
        ),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_traceback", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("job_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_job_status_created", "jobs", ["status", "created_at"], unique=False)
    op.create_index("idx_job_type_status", "jobs", ["job_type", "status"], unique=False)
    op.create_index(op.f("ix_jobs_celery_task_id"), "jobs", ["celery_task_id"], unique=True)
    op.create_index(op.f("ix_jobs_job_type"), "jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_jobs_repository_id"), "jobs", ["repository_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "module_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("module_path", sa.String(length=1000), nullable=False),
        sa.Column("module_name", sa.String(length=255), nullable=False),
        sa.Column("module_type", sa.String(length=50), nullable=False),
        sa.Column("is_package", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("key_components", sa.JSON(), nullable=True),
        sa.Column("dependencies", sa.JSON(), nullable=True),
        sa.Column("entry_points", sa.JSON(), nullable=True),
        sa.Column("file_count", sa.Integer(), nullable=True),
        sa.Column("symbol_count", sa.Integer(), nullable=True),
        sa.Column("line_count", sa.Integer(), nullable=True),
        sa.Column("complexity_score", sa.Integer(), nullable=True),
        sa.Column("generated_by", sa.String(length=100), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "module_path", name="uq_module_summary_repo_path"),
    )
    op.create_index("idx_module_repo_path", "module_summaries", ["repository_id", "module_path"], unique=False)
    op.create_index("idx_module_type", "module_summaries", ["module_type", "repository_id"], unique=False)
    op.create_index(op.f("ix_module_summaries_module_name"), "module_summaries", ["module_name"], unique=False)
    op.create_index(op.f("ix_module_summaries_module_type"), "module_summaries", ["module_type"], unique=False)
    op.create_index(op.f("ix_module_summaries_repository_id"), "module_summaries", ["repository_id"], unique=False)
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("service_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("root_namespace", sa.String(length=255), nullable=True),
        sa.Column("project_path", sa.String(length=1000), nullable=True),
        sa.Column("entry_points", sa.JSON(), nullable=True),
        sa.Column("framework_version", sa.String(length=50), nullable=True),
        sa.Column("documentation_path", sa.String(length=1000), nullable=True),
        sa.Column("last_documented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_name"), "services", ["name"], unique=False)
    op.create_index(op.f("ix_services_repository_id"), "services", ["repository_id"], unique=False)
    op.create_index(op.f("ix_services_service_type"), "services", ["service_type"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column(
            "language",
            sa.Enum(
                "JAVASCRIPT",
                "TYPESCRIPT",
                "VUE",
                "PYTHON",
                "GO",
                "JAVA",
                "MARKDOWN",
                "SQL",
                "UNKNOWN",
                name="languageenum",
            ),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("line_count", sa.Integer(), nullable=True),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["commit_id"], ["commits.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_file_language_repo", "files", ["language", "repository_id"], unique=False)
    op.create_index("idx_file_repo_path", "files", ["repository_id", "path"], unique=False)
    op.create_index(op.f("ix_files_commit_id"), "files", ["commit_id"], unique=False)
    op.create_index(op.f("ix_files_content_hash"), "files", ["content_hash"], unique=False)
    op.create_index(op.f("ix_files_language"), "files", ["language"], unique=False)
    op.create_index(op.f("ix_files_repository_id"), "files", ["repository_id"], unique=False)
    op.create_table(
        "service_repository_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("docker_service_id", sa.Integer(), nullable=True),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("target_repository_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("mapping_method", sa.String(length=50), nullable=False),
        sa.Column("mapping_metadata", sa.JSON(), nullable=True),
        sa.Column("is_manual", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["docker_service_id"], ["docker_services.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("docker_service_id", "target_repository_id", name="uq_service_mapping_service_repo"),
    )
    op.create_index("idx_service_mapping_confidence", "service_repository_mappings", ["confidence"], unique=False)
    op.create_index(
        "idx_service_mapping_docker_service", "service_repository_mappings", ["docker_service_id"], unique=False
    )
    op.create_index("idx_service_mapping_service_name", "service_repository_mappings", ["service_name"], unique=False)
    op.create_index(
        "idx_service_mapping_target_repo", "service_repository_mappings", ["target_repository_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_repository_mappings_docker_service_id"),
        "service_repository_mappings",
        ["docker_service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_repository_mappings_mapping_method"),
        "service_repository_mappings",
        ["mapping_method"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_repository_mappings_service_name"),
        "service_repository_mappings",
        ["service_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_repository_mappings_target_repository_id"),
        "service_repository_mappings",
        ["target_repository_id"],
        unique=False,
    )
    op.create_table(
        "workers",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ONLINE", "OFFLINE", "BUSY", "STARTING", "UNKNOWN", name="workerstatusenum"),
            nullable=False,
        ),
        sa.Column("current_job_id", sa.Integer(), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("queues", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["current_job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_worker_status_heartbeat", "workers", ["status", "last_heartbeat_at"], unique=False)
    op.create_index(op.f("ix_workers_current_job_id"), "workers", ["current_job_id"], unique=False)
    op.create_index(op.f("ix_workers_status"), "workers", ["status"], unique=False)
    op.create_table(
        "configuration_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("config_key", sa.String(length=500), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=True),
        sa.Column("config_type", sa.String(length=50), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=True),
        sa.Column("is_secret", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(length=1000), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_config_key", "configuration_entries", ["config_key"], unique=False)
    op.create_index("idx_config_repo_env", "configuration_entries", ["repository_id", "environment"], unique=False)
    op.create_index("idx_config_secret", "configuration_entries", ["is_secret"], unique=False)
    op.create_index(op.f("ix_configuration_entries_config_key"), "configuration_entries", ["config_key"], unique=False)
    op.create_index(
        op.f("ix_configuration_entries_environment"), "configuration_entries", ["environment"], unique=False
    )
    op.create_index(op.f("ix_configuration_entries_file_id"), "configuration_entries", ["file_id"], unique=False)
    op.create_index(
        op.f("ix_configuration_entries_repository_id"), "configuration_entries", ["repository_id"], unique=False
    )
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("package_name", sa.String(length=255), nullable=False),
        sa.Column("package_version", sa.String(length=100), nullable=True),
        sa.Column("version_constraint", sa.String(length=100), nullable=True),
        sa.Column("dependency_type", sa.String(length=50), nullable=True),
        sa.Column("is_dev_dependency", sa.Integer(), nullable=True),
        sa.Column("is_transitive", sa.Integer(), nullable=True),
        sa.Column("license", sa.String(length=100), nullable=True),
        sa.Column("file_path", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_dep_package", "dependencies", ["package_name"], unique=False)
    op.create_index("idx_dep_repo_type", "dependencies", ["repository_id", "dependency_type"], unique=False)
    op.create_index(op.f("ix_dependencies_dependency_type"), "dependencies", ["dependency_type"], unique=False)
    op.create_index(op.f("ix_dependencies_file_id"), "dependencies", ["file_id"], unique=False)
    op.create_index(op.f("ix_dependencies_package_name"), "dependencies", ["package_name"], unique=False)
    op.create_index(op.f("ix_dependencies_repository_id"), "dependencies", ["repository_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("sections", sa.JSON(), nullable=True),
        sa.Column("code_examples", sa.JSON(), nullable=True),
        sa.Column("doc_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_document_path", "documents", ["path"], unique=False)
    op.create_index("idx_document_repo_type", "documents", ["repository_id", "doc_type"], unique=False)
    op.create_index(op.f("ix_documents_doc_type"), "documents", ["doc_type"], unique=False)
    op.create_index(op.f("ix_documents_file_id"), "documents", ["file_id"], unique=False)
    op.create_index(op.f("ix_documents_repository_id"), "documents", ["repository_id"], unique=False)
    op.create_table(
        "symbols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("assembly_name", sa.String(length=255), nullable=True),
        sa.Column(
            "language",
            sa.Enum(
                "JAVASCRIPT",
                "TYPESCRIPT",
                "VUE",
                "PYTHON",
                "GO",
                "JAVA",
                "MARKDOWN",
                "SQL",
                "UNKNOWN",
                name="languageenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "FUNCTION",
                "METHOD",
                "CLASS",
                "INTERFACE",
                "STRUCT",
                "ENUM",
                "VARIABLE",
                "CONSTANT",
                "PROPERTY",
                "NAMESPACE",
                "MODULE",
                "TYPE_ALIAS",
                "DOCUMENT_SECTION",
                "CODE_EXAMPLE",
                "ENDPOINT",
                name="symbolkindenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "access_modifier",
            sa.Enum(
                "PUBLIC",
                "PRIVATE",
                "PROTECTED",
                "INTERNAL",
                "PROTECTED_INTERNAL",
                "PRIVATE_PROTECTED",
                name="accessmodifierenum",
            ),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=1000), nullable=False),
        sa.Column("fully_qualified_name", sa.String(length=2000), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("start_column", sa.Integer(), nullable=True),
        sa.Column("end_column", sa.Integer(), nullable=True),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("documentation", sa.Text(), nullable=True),
        sa.Column("structured_docs", sa.JSON(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("return_type", sa.String(length=1000), nullable=True),
        sa.Column("generic_parameters", sa.JSON(), nullable=True),
        sa.Column("constraints", sa.JSON(), nullable=True),
        sa.Column("parent_symbol_id", sa.Integer(), nullable=True),
        sa.Column("parent_name", sa.String(length=2000), nullable=True),
        sa.Column("role_tags", sa.JSON(), nullable=True),
        sa.Column("ai_enrichment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("complexity", sa.Integer(), nullable=True),
        sa.Column("complexity_score", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("is_test", sa.Integer(), nullable=True),
        sa.Column("is_generated", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("last_modified_by", sa.String(length=255), nullable=True),
        sa.Column("git_blame_commit", sa.String(length=40), nullable=True),
        sa.Column("is_partial", sa.Integer(), nullable=True),
        sa.Column("partial_definition_files", sa.JSON(), nullable=True),
        sa.Column("merged_from_partial_ids", sa.JSON(), nullable=True),
        sa.Column("is_lambda", sa.Integer(), nullable=True),
        sa.Column("closure_variables", sa.JSON(), nullable=True),
        sa.Column("linq_pattern", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["commit_id"], ["commits.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_symbol_id"], ["symbols.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_symbol_complexity", "symbols", ["complexity_score"], unique=False)
    op.create_index("idx_symbol_fqn", "symbols", ["fully_qualified_name"], unique=False)
    op.create_index("idx_symbol_name_kind", "symbols", ["name", "kind"], unique=False)
    op.create_index(op.f("ix_symbols_commit_id"), "symbols", ["commit_id"], unique=False)
    op.create_index(op.f("ix_symbols_file_id"), "symbols", ["file_id"], unique=False)
    op.create_index(op.f("ix_symbols_fully_qualified_name"), "symbols", ["fully_qualified_name"], unique=False)
    op.create_index(op.f("ix_symbols_kind"), "symbols", ["kind"], unique=False)
    op.create_index(op.f("ix_symbols_language"), "symbols", ["language"], unique=False)
    op.create_index(op.f("ix_symbols_name"), "symbols", ["name"], unique=False)
    op.create_index(op.f("ix_symbols_parent_symbol_id"), "symbols", ["parent_symbol_id"], unique=False)
    op.create_index(op.f("ix_symbols_service_id"), "symbols", ["service_id"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("chunk_subtype", sa.String(length=50), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("parent_chunk_id", sa.Integer(), nullable=True),
        sa.Column("context_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunks_content_hash"), "chunks", ["content_hash"], unique=False)
    op.create_index(op.f("ix_chunks_file_id"), "chunks", ["file_id"], unique=False)
    op.create_index(op.f("ix_chunks_parent_chunk_id"), "chunks", ["parent_chunk_id"], unique=False)
    op.create_index(op.f("ix_chunks_symbol_id"), "chunks", ["symbol_id"], unique=False)
    op.create_table(
        "event_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=True),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("event_type_name", sa.String(length=500), nullable=False),
        sa.Column("messaging_library", sa.String(length=100), nullable=True),
        sa.Column("queue_name", sa.String(length=500), nullable=True),
        sa.Column("subscription_pattern", sa.String(length=500), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("handler_class_name", sa.String(length=500), nullable=True),
        sa.Column("handler_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_event_sub_library", "event_subscriptions", ["messaging_library"], unique=False)
    op.create_index("idx_event_sub_queue", "event_subscriptions", ["queue_name"], unique=False)
    op.create_index("idx_event_sub_repo", "event_subscriptions", ["repository_id"], unique=False)
    op.create_index("idx_event_sub_symbol", "event_subscriptions", ["symbol_id"], unique=False)
    op.create_index("idx_event_sub_type", "event_subscriptions", ["event_type_name"], unique=False)
    op.create_index(
        op.f("ix_event_subscriptions_event_type_name"), "event_subscriptions", ["event_type_name"], unique=False
    )
    op.create_index(op.f("ix_event_subscriptions_file_id"), "event_subscriptions", ["file_id"], unique=False)
    op.create_index(
        op.f("ix_event_subscriptions_messaging_library"), "event_subscriptions", ["messaging_library"], unique=False
    )
    op.create_index(
        op.f("ix_event_subscriptions_repository_id"), "event_subscriptions", ["repository_id"], unique=False
    )
    op.create_index(op.f("ix_event_subscriptions_symbol_id"), "event_subscriptions", ["symbol_id"], unique=False)
    op.create_table(
        "outgoing_api_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=True),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("http_method", sa.String(length=10), nullable=False),
        sa.Column("url_pattern", sa.String(length=2000), nullable=False),
        sa.Column("call_type", sa.String(length=50), nullable=False),
        sa.Column("http_client_library", sa.String(length=100), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("is_dynamic_url", sa.Integer(), nullable=True),
        sa.Column("context_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_api_call_method", "outgoing_api_calls", ["http_method"], unique=False)
    op.create_index("idx_api_call_repo", "outgoing_api_calls", ["repository_id"], unique=False)
    op.create_index("idx_api_call_symbol", "outgoing_api_calls", ["symbol_id"], unique=False)
    op.create_index("idx_api_call_type", "outgoing_api_calls", ["call_type"], unique=False)
    op.create_index("idx_api_call_url", "outgoing_api_calls", ["url_pattern"], unique=False)
    op.create_index(op.f("ix_outgoing_api_calls_call_type"), "outgoing_api_calls", ["call_type"], unique=False)
    op.create_index(op.f("ix_outgoing_api_calls_file_id"), "outgoing_api_calls", ["file_id"], unique=False)
    op.create_index(op.f("ix_outgoing_api_calls_http_method"), "outgoing_api_calls", ["http_method"], unique=False)
    op.create_index(op.f("ix_outgoing_api_calls_repository_id"), "outgoing_api_calls", ["repository_id"], unique=False)
    op.create_index(op.f("ix_outgoing_api_calls_symbol_id"), "outgoing_api_calls", ["symbol_id"], unique=False)
    op.create_index(op.f("ix_outgoing_api_calls_url_pattern"), "outgoing_api_calls", ["url_pattern"], unique=False)
    op.create_table(
        "published_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=True),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("event_type_name", sa.String(length=500), nullable=False),
        sa.Column("messaging_library", sa.String(length=100), nullable=True),
        sa.Column("topic_name", sa.String(length=500), nullable=True),
        sa.Column("exchange_name", sa.String(length=500), nullable=True),
        sa.Column("routing_key", sa.String(length=500), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_published_event_library", "published_events", ["messaging_library"], unique=False)
    op.create_index("idx_published_event_repo", "published_events", ["repository_id"], unique=False)
    op.create_index("idx_published_event_topic", "published_events", ["topic_name"], unique=False)
    op.create_index("idx_published_event_type", "published_events", ["event_type_name"], unique=False)
    op.create_index(op.f("ix_published_events_event_type_name"), "published_events", ["event_type_name"], unique=False)
    op.create_index(op.f("ix_published_events_file_id"), "published_events", ["file_id"], unique=False)
    op.create_index(
        op.f("ix_published_events_messaging_library"), "published_events", ["messaging_library"], unique=False
    )
    op.create_index(op.f("ix_published_events_repository_id"), "published_events", ["repository_id"], unique=False)
    op.create_index(op.f("ix_published_events_symbol_id"), "published_events", ["symbol_id"], unique=False)
    op.create_table(
        "relations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_symbol_id", sa.Integer(), nullable=False),
        sa.Column("to_symbol_id", sa.Integer(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "CALLS",
                "IMPORTS",
                "EXPORTS",
                "INHERITS",
                "IMPLEMENTS",
                "USES",
                "CONTAINS",
                "OVERRIDES",
                "REFERENCES",
                name="relationtypeenum",
            ),
            nullable=False,
        ),
        sa.Column("relation_metadata", sa.JSON(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("start_column", sa.Integer(), nullable=True),
        sa.Column("end_column", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["from_symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_relation_from_type", "relations", ["from_symbol_id", "relation_type"], unique=False)
    op.create_index("idx_relation_to_type", "relations", ["to_symbol_id", "relation_type"], unique=False)
    op.create_index(op.f("ix_relations_from_symbol_id"), "relations", ["from_symbol_id"], unique=False)
    op.create_index(op.f("ix_relations_relation_type"), "relations", ["relation_type"], unique=False)
    op.create_index(op.f("ix_relations_to_symbol_id"), "relations", ["to_symbol_id"], unique=False)
    op.create_table(
        "api_endpoint_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outgoing_call_id", sa.Integer(), nullable=False),
        sa.Column("source_repository_id", sa.Integer(), nullable=False),
        sa.Column("target_symbol_id", sa.Integer(), nullable=True),
        sa.Column("target_repository_id", sa.Integer(), nullable=True),
        sa.Column("match_confidence", sa.Integer(), nullable=False),
        sa.Column("match_method", sa.String(length=50), nullable=False),
        sa.Column("match_metadata", sa.JSON(), nullable=True),
        sa.Column("gateway_repository_id", sa.Integer(), nullable=True),
        sa.Column("gateway_route_pattern", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["gateway_repository_id"], ["repositories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["outgoing_call_id"], ["outgoing_api_calls.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_repository_id"], ["repositories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_symbol_id"], ["symbols.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_api_link_confidence", "api_endpoint_links", ["match_confidence"], unique=False)
    op.create_index("idx_api_link_method", "api_endpoint_links", ["match_method"], unique=False)
    op.create_index("idx_api_link_outgoing", "api_endpoint_links", ["outgoing_call_id"], unique=False)
    op.create_index("idx_api_link_source_repo", "api_endpoint_links", ["source_repository_id"], unique=False)
    op.create_index("idx_api_link_target", "api_endpoint_links", ["target_symbol_id"], unique=False)
    op.create_index("idx_api_link_target_repo", "api_endpoint_links", ["target_repository_id"], unique=False)
    op.create_index(op.f("ix_api_endpoint_links_match_method"), "api_endpoint_links", ["match_method"], unique=False)
    op.create_index(
        op.f("ix_api_endpoint_links_outgoing_call_id"), "api_endpoint_links", ["outgoing_call_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_endpoint_links_source_repository_id"), "api_endpoint_links", ["source_repository_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_endpoint_links_target_repository_id"), "api_endpoint_links", ["target_repository_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_endpoint_links_target_symbol_id"), "api_endpoint_links", ["target_symbol_id"], unique=False
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.Vector(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_embedding_chunk", "embeddings", ["chunk_id"], unique=False)
    op.create_index("idx_embedding_symbol", "embeddings", ["symbol_id"], unique=False)
    op.create_index(op.f("ix_embeddings_chunk_id"), "embeddings", ["chunk_id"], unique=False)
    op.create_index(op.f("ix_embeddings_symbol_id"), "embeddings", ["symbol_id"], unique=False)
    op.create_table(
        "event_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("published_event_id", sa.Integer(), nullable=False),
        sa.Column("publisher_repository_id", sa.Integer(), nullable=False),
        sa.Column("event_subscription_id", sa.Integer(), nullable=False),
        sa.Column("subscriber_repository_id", sa.Integer(), nullable=False),
        sa.Column("match_confidence", sa.Integer(), nullable=False),
        sa.Column("match_method", sa.String(length=50), nullable=False),
        sa.Column("match_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_subscription_id"], ["event_subscriptions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["published_event_id"], ["published_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publisher_repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subscriber_repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_event_link_confidence", "event_links", ["match_confidence"], unique=False)
    op.create_index("idx_event_link_pub_repo", "event_links", ["publisher_repository_id"], unique=False)
    op.create_index("idx_event_link_publisher", "event_links", ["published_event_id"], unique=False)
    op.create_index("idx_event_link_sub_repo", "event_links", ["subscriber_repository_id"], unique=False)
    op.create_index("idx_event_link_subscriber", "event_links", ["event_subscription_id"], unique=False)
    op.create_index(
        op.f("ix_event_links_event_subscription_id"), "event_links", ["event_subscription_id"], unique=False
    )
    op.create_index(op.f("ix_event_links_match_method"), "event_links", ["match_method"], unique=False)
    op.create_index(op.f("ix_event_links_published_event_id"), "event_links", ["published_event_id"], unique=False)
    op.create_index(
        op.f("ix_event_links_publisher_repository_id"), "event_links", ["publisher_repository_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_links_subscriber_repository_id"), "event_links", ["subscriber_repository_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_links_subscriber_repository_id"), table_name="event_links")
    op.drop_index(op.f("ix_event_links_publisher_repository_id"), table_name="event_links")
    op.drop_index(op.f("ix_event_links_published_event_id"), table_name="event_links")
    op.drop_index(op.f("ix_event_links_match_method"), table_name="event_links")
    op.drop_index(op.f("ix_event_links_event_subscription_id"), table_name="event_links")
    op.drop_index("idx_event_link_subscriber", table_name="event_links")
    op.drop_index("idx_event_link_sub_repo", table_name="event_links")
    op.drop_index("idx_event_link_publisher", table_name="event_links")
    op.drop_index("idx_event_link_pub_repo", table_name="event_links")
    op.drop_index("idx_event_link_confidence", table_name="event_links")
    op.drop_table("event_links")
    op.drop_index(op.f("ix_embeddings_symbol_id"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_chunk_id"), table_name="embeddings")
    op.drop_index("idx_embedding_symbol", table_name="embeddings")
    op.drop_index("idx_embedding_chunk", table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(op.f("ix_api_endpoint_links_target_symbol_id"), table_name="api_endpoint_links")
    op.drop_index(op.f("ix_api_endpoint_links_target_repository_id"), table_name="api_endpoint_links")
    op.drop_index(op.f("ix_api_endpoint_links_source_repository_id"), table_name="api_endpoint_links")
    op.drop_index(op.f("ix_api_endpoint_links_outgoing_call_id"), table_name="api_endpoint_links")
    op.drop_index(op.f("ix_api_endpoint_links_match_method"), table_name="api_endpoint_links")
    op.drop_index("idx_api_link_target_repo", table_name="api_endpoint_links")
    op.drop_index("idx_api_link_target", table_name="api_endpoint_links")
    op.drop_index("idx_api_link_source_repo", table_name="api_endpoint_links")
    op.drop_index("idx_api_link_outgoing", table_name="api_endpoint_links")
    op.drop_index("idx_api_link_method", table_name="api_endpoint_links")
    op.drop_index("idx_api_link_confidence", table_name="api_endpoint_links")
    op.drop_table("api_endpoint_links")
    op.drop_index(op.f("ix_relations_to_symbol_id"), table_name="relations")
    op.drop_index(op.f("ix_relations_relation_type"), table_name="relations")
    op.drop_index(op.f("ix_relations_from_symbol_id"), table_name="relations")
    op.drop_index("idx_relation_to_type", table_name="relations")
    op.drop_index("idx_relation_from_type", table_name="relations")
    op.drop_table("relations")
    op.drop_index(op.f("ix_published_events_symbol_id"), table_name="published_events")
    op.drop_index(op.f("ix_published_events_repository_id"), table_name="published_events")
    op.drop_index(op.f("ix_published_events_messaging_library"), table_name="published_events")
    op.drop_index(op.f("ix_published_events_file_id"), table_name="published_events")
    op.drop_index(op.f("ix_published_events_event_type_name"), table_name="published_events")
    op.drop_index("idx_published_event_type", table_name="published_events")
    op.drop_index("idx_published_event_topic", table_name="published_events")
    op.drop_index("idx_published_event_repo", table_name="published_events")
    op.drop_index("idx_published_event_library", table_name="published_events")
    op.drop_table("published_events")
    op.drop_index(op.f("ix_outgoing_api_calls_url_pattern"), table_name="outgoing_api_calls")
    op.drop_index(op.f("ix_outgoing_api_calls_symbol_id"), table_name="outgoing_api_calls")
    op.drop_index(op.f("ix_outgoing_api_calls_repository_id"), table_name="outgoing_api_calls")
    op.drop_index(op.f("ix_outgoing_api_calls_http_method"), table_name="outgoing_api_calls")
    op.drop_index(op.f("ix_outgoing_api_calls_file_id"), table_name="outgoing_api_calls")
    op.drop_index(op.f("ix_outgoing_api_calls_call_type"), table_name="outgoing_api_calls")
    op.drop_index("idx_api_call_url", table_name="outgoing_api_calls")
    op.drop_index("idx_api_call_type", table_name="outgoing_api_calls")
    op.drop_index("idx_api_call_symbol", table_name="outgoing_api_calls")
    op.drop_index("idx_api_call_repo", table_name="outgoing_api_calls")
    op.drop_index("idx_api_call_method", table_name="outgoing_api_calls")
    op.drop_table("outgoing_api_calls")
    op.drop_index(op.f("ix_event_subscriptions_symbol_id"), table_name="event_subscriptions")
    op.drop_index(op.f("ix_event_subscriptions_repository_id"), table_name="event_subscriptions")
    op.drop_index(op.f("ix_event_subscriptions_messaging_library"), table_name="event_subscriptions")
    op.drop_index(op.f("ix_event_subscriptions_file_id"), table_name="event_subscriptions")
    op.drop_index(op.f("ix_event_subscriptions_event_type_name"), table_name="event_subscriptions")
    op.drop_index("idx_event_sub_type", table_name="event_subscriptions")
    op.drop_index("idx_event_sub_symbol", table_name="event_subscriptions")
    op.drop_index("idx_event_sub_repo", table_name="event_subscriptions")
    op.drop_index("idx_event_sub_queue", table_name="event_subscriptions")
    op.drop_index("idx_event_sub_library", table_name="event_subscriptions")
    op.drop_table("event_subscriptions")
    op.drop_index(op.f("ix_chunks_symbol_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_parent_chunk_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_file_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_content_hash"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_symbols_service_id"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_parent_symbol_id"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_name"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_language"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_kind"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_fully_qualified_name"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_file_id"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_commit_id"), table_name="symbols")
    op.drop_index("idx_symbol_name_kind", table_name="symbols")
    op.drop_index("idx_symbol_fqn", table_name="symbols")
    op.drop_index("idx_symbol_complexity", table_name="symbols")
    op.drop_table("symbols")
    op.drop_index(op.f("ix_documents_repository_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_file_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_doc_type"), table_name="documents")
    op.drop_index("idx_document_repo_type", table_name="documents")
    op.drop_index("idx_document_path", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_dependencies_repository_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_package_name"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_file_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_dependency_type"), table_name="dependencies")
    op.drop_index("idx_dep_repo_type", table_name="dependencies")
    op.drop_index("idx_dep_package", table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_configuration_entries_repository_id"), table_name="configuration_entries")
    op.drop_index(op.f("ix_configuration_entries_file_id"), table_name="configuration_entries")
    op.drop_index(op.f("ix_configuration_entries_environment"), table_name="configuration_entries")
    op.drop_index(op.f("ix_configuration_entries_config_key"), table_name="configuration_entries")
    op.drop_index("idx_config_secret", table_name="configuration_entries")
    op.drop_index("idx_config_repo_env", table_name="configuration_entries")
    op.drop_index("idx_config_key", table_name="configuration_entries")
    op.drop_table("configuration_entries")
    op.drop_index(op.f("ix_workers_status"), table_name="workers")
    op.drop_index(op.f("ix_workers_current_job_id"), table_name="workers")
    op.drop_index("idx_worker_status_heartbeat", table_name="workers")
    op.drop_table("workers")
    op.drop_index(op.f("ix_service_repository_mappings_target_repository_id"), table_name="service_repository_mappings")
    op.drop_index(op.f("ix_service_repository_mappings_service_name"), table_name="service_repository_mappings")
    op.drop_index(op.f("ix_service_repository_mappings_mapping_method"), table_name="service_repository_mappings")
    op.drop_index(op.f("ix_service_repository_mappings_docker_service_id"), table_name="service_repository_mappings")
    op.drop_index("idx_service_mapping_target_repo", table_name="service_repository_mappings")
    op.drop_index("idx_service_mapping_service_name", table_name="service_repository_mappings")
    op.drop_index("idx_service_mapping_docker_service", table_name="service_repository_mappings")
    op.drop_index("idx_service_mapping_confidence", table_name="service_repository_mappings")
    op.drop_table("service_repository_mappings")
    op.drop_index(op.f("ix_files_repository_id"), table_name="files")
    op.drop_index(op.f("ix_files_language"), table_name="files")
    op.drop_index(op.f("ix_files_content_hash"), table_name="files")
    op.drop_index(op.f("ix_files_commit_id"), table_name="files")
    op.drop_index("idx_file_repo_path", table_name="files")
    op.drop_index("idx_file_language_repo", table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_services_service_type"), table_name="services")
    op.drop_index(op.f("ix_services_repository_id"), table_name="services")
    op.drop_index(op.f("ix_services_name"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_module_summaries_repository_id"), table_name="module_summaries")
    op.drop_index(op.f("ix_module_summaries_module_type"), table_name="module_summaries")
    op.drop_index(op.f("ix_module_summaries_module_name"), table_name="module_summaries")
    op.drop_index("idx_module_type", table_name="module_summaries")
    op.drop_index("idx_module_repo_path", table_name="module_summaries")
    op.drop_table("module_summaries")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_repository_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_job_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_celery_task_id"), table_name="jobs")
    op.drop_index("idx_job_type_status", table_name="jobs")
    op.drop_index("idx_job_status_created", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_gateway_routes_upstream_host"), table_name="gateway_routes")
    op.drop_index(op.f("ix_gateway_routes_repository_id"), table_name="gateway_routes")
    op.drop_index(op.f("ix_gateway_routes_gateway_type"), table_name="gateway_routes")
    op.drop_index(op.f("ix_gateway_routes_downstream_path_template"), table_name="gateway_routes")
    op.drop_index("idx_gateway_route_upstream_host", table_name="gateway_routes")
    op.drop_index("idx_gateway_route_type", table_name="gateway_routes")
    op.drop_index("idx_gateway_route_repo", table_name="gateway_routes")
    op.drop_index("idx_gateway_route_downstream", table_name="gateway_routes")
    op.drop_table("gateway_routes")
    op.drop_index(op.f("ix_docker_services_service_name"), table_name="docker_services")
    op.drop_index(op.f("ix_docker_services_repository_id"), table_name="docker_services")
    op.drop_index("idx_docker_service_repo", table_name="docker_services")
    op.drop_index("idx_docker_service_name", table_name="docker_services")
    op.drop_index("idx_docker_service_image", table_name="docker_services")
    op.drop_table("docker_services")
    op.drop_index(op.f("ix_commits_sha"), table_name="commits")
    op.drop_index(op.f("ix_commits_repository_id"), table_name="commits")
    op.drop_table("commits")
    op.drop_index(op.f("ix_repositories_status"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_provider"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_gitlab_project_id"), table_name="repositories")
    op.drop_index("idx_repo_status_updated", table_name="repositories")
    op.drop_index("idx_repo_provider_path", table_name="repositories")
    op.drop_index("idx_repo_gitlab_project", table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_index("idx_audit_user_timestamp", table_name="audit_logs")
    op.drop_index("idx_audit_event_timestamp", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
